### ISSUE TITLE
Some Icons Have Different Sizes

### ISSUE THREAD

**Issue by amature0000** [nvigneux/Helldivers-2-Stratagems-icons-svg#16]
Hello,
Thank you for your project! I used the icons to create a simple toy project and successfully deployed it.

The recently changed icons have different sizes(e.g. stalwart). This is not a problem at all, but I wanted to know that it has been noticed as known issue.

I found that "recently changed icons" have defined widths and heights of 126 pixels.
Other icons do not define widths and heights:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 126 126" ...>`

**Comment by nvigneux** [comment]
Hello,

Thank you for your kind feedback and for using the icons in your project—I’m glad to hear it worked well for you!

Regarding the issue with the recently changed icons having defined widths and heights, I appreciate you bringing this to my attention. This happened due to a change in the SVG optimization tool I’ve been using. I’ll adjust the configuration to prioritize viewBox instead of width and height, as it was previously, to maintain consistency across all icons.

Thanks again for pointing this out, and feel free to reach out if you encounter anything else! 😊
